# Generated by Django 5.1.3 on 2024-11-26 15:43

import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitimas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitima',
            name='foto',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='vitimas', variations={}, verbose_name='Foto'),
        ),
    ]
