# Generated by Django 5.1.3 on 2024-11-27 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abrigos', '0001_initial'),
        ('vitimas', '0002_vitima_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitima',
            name='abrigo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vitimas', to='abrigos.abrigo'),
        ),
        migrations.AlterField(
            model_name='vitima',
            name='necessidades_especiais',
            field=models.CharField(help_text='Necessidades especiais da vítima', max_length=50, verbose_name='Necessidades especiais'),
        ),
    ]
