# Generated by Django 5.1.3 on 2024-11-27 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abrigos', '0001_initial'),
        ('vitimas', '0003_vitima_abrigo_alter_vitima_necessidades_especiais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitima',
            name='abrigo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vitimas', to='abrigos.abrigo'),
            preserve_default=False,
        ),
    ]
