# Generated by Django 5.1.3 on 2024-12-10 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistencia',
            name='descricao',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='assistencia',
            name='prioridade',
            field=models.CharField(choices=[('B', 'Baixa'), ('M', 'Média'), ('A', 'Alta')], default='B', help_text='Prioridade do serviço', max_length=20, verbose_name='Prioridade'),
        ),
    ]
