# Generated by Django 5.1.3 on 2024-11-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo', max_length=100, verbose_name='Nome')),
                ('idade', models.IntegerField(help_text='Idade da pessoa', verbose_name='Idade')),
                ('fone', models.CharField(help_text='Telefone de contato', max_length=15, verbose_name='Telefone')),
                ('endereco', models.CharField(help_text='Endereço da pessoa', max_length=100, verbose_name='Endereço')),
                ('email', models.EmailField(help_text='E-mail da pessoa', max_length=100, verbose_name='E-mail')),
                ('cpf', models.CharField(help_text='CPF da pessoa', max_length=14, unique=True, verbose_name='CPF')),
                ('sexo', models.CharField(help_text='Sexo da pessoa', max_length=1, verbose_name='Sexo')),
                ('especialidade', models.CharField(help_text='Especialidade do voluntário', max_length=100, verbose_name='Especialidade')),
                ('disponibilidade', models.CharField(help_text='Horários disponíveis', max_length=100, verbose_name='Disponibilidade')),
                ('experiencia', models.CharField(help_text='Experiência anterior', max_length=100, verbose_name='Experiência')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
