# Generated by Django 5.1.3 on 2024-11-27 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voluntarios', '0002_alter_voluntario_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abrigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do abrigo', max_length=100, verbose_name='Nome do abrigo')),
                ('endereco', models.CharField(help_text='Endereço do abrigo', max_length=100, verbose_name='Endereço')),
                ('capacidade', models.IntegerField(help_text='Capacidade do abrigo', verbose_name='Capacidade')),
                ('fone', models.CharField(help_text='Telefone do abrigo', max_length=20, verbose_name='Telefone')),
                ('tipo', models.CharField(help_text='Tipo do abrigo', max_length=20, verbose_name='Tipo')),
                ('descricao', models.TextField(help_text='Descrição do abrigo', verbose_name='Descrição')),
                ('status', models.CharField(help_text='Status do abrigo', max_length=20, verbose_name='Status')),
                ('voluntarios', models.ManyToManyField(help_text='Voluntários trabalhando neste abrigo', related_name='abrigos', to='voluntarios.voluntario')),
            ],
            options={
                'verbose_name': 'Abrigo',
                'verbose_name_plural': 'Abrigos',
            },
        ),
    ]
