# Generated by Django 5.1.3 on 2024-11-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abrigos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abrigo',
            name='descricao',
            field=models.CharField(help_text='Descrição do abrigo', max_length=50, verbose_name='Descrição'),
        ),
    ]
